### ISSUE TITLE
so what does this do exactly

### ISSUE THREAD

**Issue by LBlazen** [AzaleaGMD/GDPS-Addon#1]
it just adds like a cut button and mod badges or its incomplete

**Comment by GGaMErZZ** [comment]
its code for xgdps libcurl.dll

**Comment by fancythedeveloper** [comment]
any way to compile this tho?

**Comment by anonymousGDplayer** [comment]
idk

**Comment by anonymousGDplayer** [comment]
> any way to compile this tho?


idk man. maybe visual studio?
